### ISSUE TITLE
Using Flashbar in java-only projects requires kotlin-stdlib dependency

### ISSUE THREAD

**Issue by ardevd** [aritraroy/Flashbar#4] opened 2018-05-02 14:51 UTC
Not sure if this is by design, but using Flashbar in my non-kotlin enabled Android project resulted in an immediate crash on application run with a ClassNotFoundException. I had to add the kotlin-stdlib dependency to my app gradle in order to get it working.

Would be nice if there was a way around that.

**Comment by aritraroy** [comment] 2018-05-05 19:00
Thanks for reporting this.

This is definitely a bug and not by design. I will dig deeper into it and get back to you soon. Can you also give me the crash log that you got? Will help me debug faster.

**Comment by soundlicious** [comment] 2018-05-08 08:57
Here the same crash Report if needed : 
05-08 16:53:07.422 13258-13258/com.evoke.evokecompanionapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.evoke.evokecompanionapp, PID: 13258
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.andrognito.flashbar.Flashbar$Builder.<init>(Unknown Source:2)
        at com.evoke.evokecompanionapp.views.map.MapActivity.onCreate(MapActivity.java:73)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7428)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/base.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_resources_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/lib/arm64, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/base.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
05-08 16:53:07.423 13258-13258/com.evoke.evokecompanionapp E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 14 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.evoke.evokecompanionapp--OZfWxkzjrePmqVR9qt_sg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
        at android.app.LoadedApk.getResources(LoadedApk.java:996)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6401)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)
        		... 6 more

**Comment by aritraroy** [comment] 2018-05-08 18:22
This issue should be fixed in the latest version 1.0.2. Please update and let me know if you face any issues.

**Comment by soundlicious** [comment] 2018-05-09 06:53
kotlin-stdlib removed from my dependencies and everything work. Issue solved.

**Comment by aritraroy** [comment] 2018-05-09 07:03
Cool. Closing the issue.

**Closed by aritraroy** 2018-05-09 07:03 UTC
Labels: bug
